# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - release
  - devel
  - oldrel

repos:
  CRAN: https://cloud.r-project.org

warnings_are_errors: false

deploy.skip_cleanup: true

os:
  - linux

sudo: false
dist: trusty

cache:
  - packages

latex: true
pandoc: true

notifications:
  email:
    on_success: never
    on_failure: never

addons:
  apt_packages:
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - libudunits2-dev
