# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - release
  - devel
  - oldrel

repos:
  CRAN: https://cloud.r-project.org

warnings_are_errors: false

deploy.skip_cleanup: true

os:
  - linux

sudo: false
dist: trusty

cache:
  - packages

before_install:
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

#before_install:
#  - wget http://download.osgeo.org/gdal/2.0.1/gdal-2.0.1.tar.gz
#  - tar zxf gdal-2.0.1.tar.gz
#  - cd gdal-2.0.1
#  - ./configure --prefix=/usr
#  - make
#  - sudo make install

latex: true
pandoc: true

notifications:
  email:
    on_success: never
    on_failure: never

r_github_packages:
  - r-lib/covr

after_success:
      - Rscript -e 'covr::codecov()'

#addons:
#  apt_packages:
#      - libgdal-dev
#      - libproj-dev
#      - libgeos-dev
#      - libudunits2-dev
