# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - release
  - devel

repos:
  CRAN: https://cloud.r-project.org

r_paackages:
  - Matrix-1.2.15

warnings_are_errors: false

deploy.skip_cleanup: true

sudo: required
dist: ubuntu

cache:
  - packages
  - ccache

latex: false

addons:
  apt_packages:
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - libudunits2-dev --configure-args='--with-udunits2-lib=/usr/local/lib'
