# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - release
  - devel

repos:
  CRAN: https://cloud.r-project.org

warnings_are_errors: false

deploy.skip_cleanup: true

sudo: required
dist: trusty

cache:
  - packages
  - ccache

latex: false

addons:
  apt_packages:
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - libudunits2-dev
